site_name: Proyecto Intermodular ASIR

nav:
  - Inicio: index.md
  - Introducción: 01_introduccion.md
  - Requisitos: 02_requisitos.md
  - Solución ASO: 04_solucion_aso.md
  - Solución ASGBD: 05_solucion_asgbd.md
